import { ParsedAnalyzerMessage, ParsedItem } from './astmParser';

/**
 * Parses CSV / Delimited files generated by analyzers or folder watchers.
 * Supports UTF-8 BOM stripping, RFC 4180 quoted CSV parsing, and Key-Value text formats.
 */
export function parseCsvOrText(raw: string): ParsedAnalyzerMessage {
  // Strip UTF-8 BOM if present
  const cleanRaw = raw.replace(/^\uFEFF/, '');

  const lines = cleanRaw
    .replace(/\r\n/g, '\n')
    .replace(/\r/g, '\n')
    .split('\n')
    .map((l) => l.trim())
    .filter(Boolean);

  let sampleNumber: number | undefined = undefined;
  let sampleBarcode: string | undefined = undefined;
  let patientName: string | undefined = undefined;
  const items: ParsedItem[] = [];

  // Helper for RFC 4180 CSV line split
  const splitCsvLine = (text: string, delim: string): string[] => {
    const result: string[] = [];
    let current = '';
    let inQuotes = false;
    for (let i = 0; i < text.length; i++) {
      const char = text[i];
      if (char === '"' || char === "'") {
        inQuotes = !inQuotes;
      } else if (char === delim && !inQuotes) {
        result.push(current.trim().replace(/^["']|["']$/g, ''));
        current = '';
      } else {
        current += char;
      }
    }
    result.push(current.trim().replace(/^["']|["']$/g, ''));
    return result;
  };

  for (const line of lines) {
    if (line.includes(',') || line.includes('\t') || line.includes(';')) {
      const delimiter = line.includes(',') ? ',' : line.includes('\t') ? '\t' : ';';
      const cols = splitCsvLine(line, delimiter);

      // If header line, skip (normalized check)
      const normCol0 = cols[0].toUpperCase().replace(/[\s_-]/g, '');
      if (['SAMPLE', 'SAMPLEID', 'ID', 'BARCODE', 'SPECIMEN', 'PATIENTID', 'PATIENT', 'TEST', 'TESTCODE'].includes(normCol0)) {
        continue;
      }

      // Format: SampleID, TestCode, Value, Unit, Flag
      if (cols.length >= 3) {
        const rawSample = cols[0];
        if (rawSample && !sampleBarcode) {
          sampleBarcode = rawSample;
          const num = rawSample.match(/\d+/);
          if (num) sampleNumber = parseInt(num[0], 10);
        }

        const testCode = cols[1]?.toUpperCase();
        const value = cols[2];
        const unit = cols[3] || '';
        const flag = cols[4] || '';

        if (testCode && value) {
          const cleanFlag = flag.toUpperCase();
          const isAbnormal = ['H', 'L', 'A', 'HIGH', 'LOW', 'POSITIVE', '+', '-'].includes(cleanFlag);
          items.push({
            testCode,
            value,
            unit: unit || undefined,
            flags: flag || undefined,
            isAbnormal,
          });
        }
      }
    } else if (line.includes(':') || line.includes('=')) {
      // Key-Value format: "Sample: 105" or "WBC: 7.4"
      const parts = line.split(/[:=]/).map((p) => p.trim());
      const key = parts[0]?.toUpperCase();
      const val = parts[1] || '';

      if (['SAMPLE', 'SAMPLEID', 'SAMPLE_ID', 'BARCODE', 'ID', 'SID'].includes(key.replace(/[\s_-]/g, ''))) {
        sampleBarcode = val;
        const num = val.match(/\d+/);
        if (num) sampleNumber = parseInt(num[0], 10);
      } else if (['NAME', 'PATIENT', 'PATIENT_NAME'].includes(key.replace(/[\s_-]/g, ''))) {
        patientName = val;
      } else if (key && val) {
        // Assume this is a test key-value (e.g. WBC: 7.5 10^3/uL)
        const valParts = val.split(' ');
        const testValue = valParts[0];
        const unit = valParts.slice(1).join(' ');

        items.push({
          testCode: key,
          value: testValue,
          unit: unit || undefined,
        });
      }
    }
  }

  return {
    protocol: 'CSV_DELIMITED',
    sampleNumber,
    sampleBarcode,
    patientName,
    timestamp: new Date(),
    items,
    rawMessage: raw,
  };
}
